#ifndef INCLUDE_UNSECURE_SOCKET_THREAD_H_
#define INCLUDE_UNSECURE_SOCKET_THREAD_H_

#include <pthread.h>
#include <secure_socket_thread.h>

/**
 * <pre>
 * Function executed on generation of unsecure socket to listin for connections
 * <pre>
 * 
 * @param[in] arg a pointer to a structure containing the 
 *                socket id for that thread and the key table
 *                mutex.
 *
 * @return none
 */
void unsecure_socket_thread(void *arg);

/**
 * <pre>
 * Function executed on each thread generated by connection to unsecure socket
 * <pre>
 * 
 * @param[in] arg a pointer to a structure containing the 
 *                socket id for that thread and the key table
 *                mutex.
 *
 * @return none
 */
void unsecure_socket_process(void *arg);

#endif
